/*
 * Copyright Splunk Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.splunk.opentelemetry.instrumentation.jdbc;

import static com.splunk.opentelemetry.instrumentation.jdbc.AbstractDbContextPropagationTest.Capability.COLUMN_INDEXES;
import static com.splunk.opentelemetry.instrumentation.jdbc.AbstractDbContextPropagationTest.Capability.LARGE_OPERATIONS;
import static org.junit.jupiter.api.Assumptions.assumeTrue;
import static org.junit.jupiter.api.Named.named;

import io.opentelemetry.api.trace.SpanContext;
import io.opentelemetry.instrumentation.testing.internal.AutoCleanupExtension;
import io.opentelemetry.instrumentation.testing.junit.InstrumentationExtension;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Arrays;
import java.util.List;
import java.util.concurrent.atomic.AtomicReference;
import org.junit.jupiter.api.extension.RegisterExtension;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

public abstract class AbstractDbContextPropagationTest {
  @RegisterExtension static final AutoCleanupExtension cleanup = AutoCleanupExtension.create();

  protected abstract InstrumentationExtension getTesting();

  private static List<Arguments> contextPropagationArguments() {
    return Arrays.asList(
        // Statement tests
        Arguments.of(
            named(
                "Statement.executeQuery",
                (Action)
                    connection -> {
                      try (Statement statement = connection.createStatement()) {
                        statement.executeQuery("SELECT 1");
                      }
                    })),
        Arguments.of(
            named(
                "Statement.executeUpdate",
                (Action)
                    connection -> {
                      try (Statement statement = connection.createStatement()) {
                        statement.executeUpdate("INSERT INTO test_table VALUES(1)");
                      }
                    })),
        Arguments.of(
            named(
                "Statement.executeUpdate with autoGeneratedKeys",
                (Action)
                    connection -> {
                      try (Statement statement = connection.createStatement()) {
                        statement.executeUpdate(
                            "INSERT INTO test_table VALUES(1)", Statement.NO_GENERATED_KEYS);
                      }
                    })),
        Arguments.of(
            named(
                "Statement.executeUpdate with columnIndexes",
                Action.of(
                    connection -> {
                      try (Statement statement = connection.createStatement()) {
                        statement.executeUpdate("INSERT INTO test_table VALUES(1)", new int[] {1});
                      }
                    },
                    COLUMN_INDEXES))),
        Arguments.of(
            named(
                "Statement.executeUpdate with columnNames",
                (Action)
                    connection -> {
                      try (Statement statement = connection.createStatement()) {
                        statement.executeUpdate(
                            "INSERT INTO test_table VALUES(1)", new String[] {"value"});
                      }
                    })),
        Arguments.of(
            named(
                "Statement.execute",
                (Action)
                    connection -> {
                      try (Statement statement = connection.createStatement()) {
                        statement.execute("SELECT 1");
                      }
                    })),
        Arguments.of(
            named(
                "Statement.execute with autoGeneratedKeys",
                (Action)
                    connection -> {
                      try (Statement statement = connection.createStatement()) {
                        statement.execute(
                            "INSERT INTO test_table VALUES(1)", Statement.NO_GENERATED_KEYS);
                      }
                    })),
        Arguments.of(
            named(
                "Statement.execute with columnIndexes",
                Action.of(
                    connection -> {
                      try (Statement statement = connection.createStatement()) {
                        statement.execute("INSERT INTO test_table VALUES(1)", new int[] {1});
                      }
                    },
                    COLUMN_INDEXES))),
        Arguments.of(
            named(
                "Statement.execute with columnNames",
                (Action)
                    connection -> {
                      try (Statement statement = connection.createStatement()) {
                        statement.execute(
                            "INSERT INTO test_table VALUES(1)", new String[] {"value"});
                      }
                    })),
        Arguments.of(
            named(
                "Statement.executeBatch",
                (Action)
                    connection -> {
                      try (Statement statement = connection.createStatement()) {
                        statement.addBatch("INSERT INTO test_table VALUES(1)");
                        statement.executeBatch();
                      }
                    })),
        Arguments.of(
            named(
                "Statement.executeLargeBatch",
                Action.of(
                    connection -> {
                      try (Statement statement = connection.createStatement()) {
                        statement.addBatch("INSERT INTO test_table VALUES(1)");
                        statement.executeLargeBatch();
                      }
                    },
                    LARGE_OPERATIONS))),
        Arguments.of(
            named(
                "Statement.executeLargeUpdate",
                Action.of(
                    connection -> {
                      try (Statement statement = connection.createStatement()) {
                        statement.executeLargeUpdate("INSERT INTO test_table VALUES(1)");
                      }
                    },
                    LARGE_OPERATIONS))),
        Arguments.of(
            named(
                "Statement.executeLargeUpdate with autoGeneratedKeys",
                Action.of(
                    connection -> {
                      try (Statement statement = connection.createStatement()) {
                        statement.executeLargeUpdate(
                            "INSERT INTO test_table VALUES(1)", Statement.NO_GENERATED_KEYS);
                      }
                    },
                    LARGE_OPERATIONS))),
        Arguments.of(
            named(
                "Statement.executeLargeUpdate with columnIndexes",
                Action.of(
                    connection -> {
                      try (Statement statement = connection.createStatement()) {
                        statement.executeLargeUpdate(
                            "INSERT INTO test_table VALUES(1)", new int[] {1});
                      }
                    },
                    COLUMN_INDEXES,
                    LARGE_OPERATIONS))),
        Arguments.of(
            named(
                "Statement.executeLargeUpdate with columnNames",
                Action.of(
                    connection -> {
                      try (Statement statement = connection.createStatement()) {
                        statement.executeLargeUpdate(
                            "INSERT INTO test_table VALUES(1)", new String[] {"value"});
                      }
                    },
                    LARGE_OPERATIONS))),
        // PreparedStatement tests
        Arguments.of(
            named(
                "PreparedStatement.executeQuery",
                (Action)
                    connection -> {
                      try (PreparedStatement statement = connection.prepareStatement("SELECT 1")) {
                        statement.executeQuery();
                      }
                    })),
        Arguments.of(
            named(
                "PreparedStatement.executeUpdate",
                (Action)
                    connection -> {
                      try (PreparedStatement statement =
                          connection.prepareStatement("INSERT INTO test_table VALUES(1)")) {
                        statement.executeUpdate();
                      }
                    })),
        Arguments.of(
            named(
                "PreparedStatement.execute",
                (Action)
                    connection -> {
                      try (PreparedStatement statement = connection.prepareStatement("SELECT 1")) {
                        statement.execute();
                      }
                    })),
        Arguments.of(
            named(
                "PreparedStatement.executeLargeUpdate",
                Action.of(
                    connection -> {
                      try (PreparedStatement statement =
                          connection.prepareStatement("INSERT INTO test_table VALUES(1)")) {
                        statement.executeLargeUpdate();
                      }
                    },
                    LARGE_OPERATIONS))),
        Arguments.of(
            named(
                "PreparedStatement.executeBatch",
                (Action)
                    connection -> {
                      try (PreparedStatement statement =
                          connection.prepareStatement("INSERT INTO test_table VALUES(1)")) {
                        statement.addBatch();
                        statement.executeBatch();
                      }
                    })),
        Arguments.of(
            named(
                "PreparedStatement.executeLargeBatch",
                Action.of(
                    connection -> {
                      try (PreparedStatement statement =
                          connection.prepareStatement("INSERT INTO test_table VALUES(1)")) {
                        statement.addBatch();
                        statement.executeLargeBatch();
                      }
                    },
                    LARGE_OPERATIONS))),
        // CallableStatement tests
        Arguments.of(
            named(
                "CallableStatement.execute",
                (Action)
                    connection -> {
                      try (CallableStatement statement = connection.prepareCall("SELECT 1")) {
                        statement.execute();
                      }
                    })));
  }

  protected abstract Connection newConnection() throws SQLException;

  @ParameterizedTest
  @MethodSource("contextPropagationArguments")
  void contextPropagation(Action action) throws Exception {
    action.checkCapabilities(this);

    Connection connection = newConnection();
    cleanup.deferCleanup(connection);

    assertBeforeQuery(connection);

    getTesting().runWithSpan("parent", () -> action.accept(connection));

    AtomicReference<SpanContext> jdbcSpan = new AtomicReference<>();
    AtomicReference<SpanContext> parentSpan = new AtomicReference<>();
    getTesting()
        .waitAndAssertTraces(
            trace ->
                trace.hasSpansSatisfyingExactly(
                    span -> {
                      span.hasName("parent").hasNoParent();
                      parentSpan.set(span.actual().getSpanContext());
                    },
                    span -> {
                      span.hasParent(trace.getSpan(0));
                      jdbcSpan.set(span.actual().getSpanContext());
                    }));

    assertAfterQuery(connection, parentSpan.get(), jdbcSpan.get());
  }

  protected abstract void assertBeforeQuery(Connection connection) throws Exception;

  protected abstract void assertAfterQuery(
      Connection connection, SpanContext parent, SpanContext jdbc) throws Exception;

  protected boolean supportsColumnIndexes() {
    return true;
  }

  protected boolean supportsLarge() {
    return true;
  }

  @FunctionalInterface
  interface Action {
    void accept(Connection connection) throws Exception;

    default void checkCapabilities(AbstractDbContextPropagationTest test) {}

    static Action of(Action action, Capability... capabilities) {
      return new DefaultAction(action, capabilities) {
        @Override
        public void accept(Connection connection) throws Exception {
          action.accept(connection);
        }
      };
    }
  }

  static class DefaultAction implements Action {
    private final Action delegate;
    private final Capability[] capabilities;

    DefaultAction(Action delegate, Capability... capabilities) {
      this.delegate = delegate;
      this.capabilities = capabilities;
    }

    @Override
    public void accept(Connection connection) throws Exception {
      delegate.accept(connection);
    }

    @Override
    public void checkCapabilities(AbstractDbContextPropagationTest test) {
      for (Capability capability : capabilities) {
        switch (capability) {
          case COLUMN_INDEXES:
            assumeTrue(test.supportsColumnIndexes());
            break;
          case LARGE_OPERATIONS:
            assumeTrue(test.supportsLarge());
            break;
        }
      }
    }
  }

  enum Capability {
    COLUMN_INDEXES,
    LARGE_OPERATIONS
  }
}
