# To build an auto-instrumentation image for Java, please:
#  - Grant the necessary access to the jar.
#  - Symlink the jar to `/javaagent.jar` to support compatability with the
#    https://github.com/open-telemetry/opentelemetry-operator project.
#  - For this docker image to be used for auto-instrumentation by container injection, we use the
#    busybox image because it contains the Linux command cp which must be available.
FROM busybox

LABEL org.opencontainers.image.source="https://github.com/signalfx/splunk-otel-java"
LABEL org.opencontainers.image.description="Splunk Distribution of OpenTelemetry Java Instrumentation"

ARG RELEASE_VER
ARG JAR_FILE=splunk-otel-javaagent.jar
ENV RELEASE_VER=$RELEASE_VER

ADD https://github.com/signalfx/splunk-otel-java/releases/download/${RELEASE_VER}/${JAR_FILE} /
RUN chmod 644 "/${JAR_FILE}"
RUN ln -s "/${JAR_FILE}" /javaagent.jar
