#
# OTEL Extension Properties - NOTE: These are System Properties and can be overriden if set on the startup command line
#
#---- Enable full OTEL for CSaaS (CSA Controller) and for the Pipeline (OTIS, AppD Cloud) - send Event Signal
###########  Set to enable sending to CSA Controller in CSaas - if OTEL and disabled - it means standalone mode
multi.tenant.agent.otel.csaas.enabled=false
###########  Set to enable sending Events, etc. to the OTEL Collector as Events and Span Events, Attributes, etc.
multi.tenant.agent.otel.pipeline.enabled=true
###########  Enable Trace History - Keeps the last 100 Traces in Memory for Debugging - Not for Production
# multi.tenant.agent.otel.trace.history.enabled=false
###########  Set to enable sending standalone Events not attached to a Span
multi.tenant.agent.otel.send.log.events=false
###########  Set to enable sending Generic Data as Standalone Events
multi.tenant.agent.otel.send.fake.log.events=true
###########  Enable Diagnostics Server - Not for Production
# multi.tenant.agent.enable.diagnostics.server=true
########### Do we allow Security Events
argento.allow.security.events=false
########### Do we allow blocking
argento.disable.blocking=true 
########### Enable Full Regression Testing - Not for Production
# multi.tenant.agent.regression.testing=true
########### Allow OTEL Instrumentation - This will allow instrumentation for tracking Spans to Add to Events
# multi.tenant.agent.allow.otel.instrumentation=false
########### Set Fragmentatton Artifacts Per Fragmentatton
argento.max.post.fragment.event.size.property=5
########### This Triggers Fragmentatton
# argento.alert.on.http.post.size.property=65000
#
#---- AppDynamics Configuration to find CSaaS CSA Controller - app/tier/node will be defined via the OSS Agent otel.resource.attributes=
#
###########  CSaas Host
# appdynamics.controller.hostName=PROVIDE_HOST_NAME
###########  SSL (actually TLS)
# appdynamics.controller.ssl.enabled=true
###########  TLS Port
# appdynamics.controller.port=443
###########  CSaas Tenant
# appdynamics.agent.accountName=PROVIDE_NAME
###########  CSaas Tenant Key
# appdynamics.agent.accountAccessKey=PROVIDE_KEY
#
#---- For OTIS Registration (Disabled by default - need more work to enable Java 9+)
#
###########  Use Agent OTEL Exporter to register with OTIS (if value > 0)
# multi.tenant.agent.local.otis.registration.attempts=0
########### OTIS Endpoint
# multi.tenant.agent.local.otis.registration.endpoint=https://pdx-sls-agent-api.saas.appdynamics.com/v1/traces
########### OTIS Endpoint API Key
# multi.tenant.agent.local.otis.registration.endpoint.apikey=PROVIDE_KEY
