name: CI build

concurrency:
  group: ci
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - v[0-9]+.[0-9]+.x

jobs:
  check-links:
    # release branches are excluded
    if: "!startsWith(github.ref_name, 'release/')"
    uses: ./.github/workflows/reusable-link-check.yml

  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up JDK 17 for running Gradle
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0

      - name: Build and test
        run: ./gradlew build

      - name: Build scan
        if: ${{ !cancelled() && hashFiles('build-scan.txt') != '' }}
        run: cat build-scan.txt

  test-latest-deps:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up JDK 17 for running Gradle
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0

      - name: Build and test
        run: ./gradlew check -x spotlessCheck -PtestLatestDeps=true

      - name: Build scan
        if: ${{ !cancelled() && hashFiles('build-scan.txt') != '' }}
        run: cat build-scan.txt

  setup-muzzle-matrix:
    runs-on: ubuntu-24.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up JDK 17 for running Gradle
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0

      - id: set-matrix
        run: echo "matrix={\"module\":[\"$(./gradlew -q instrumentation:listMuzzleInstrumentations | xargs echo | sed 's/ /","/g')\"]}" >> $GITHUB_OUTPUT

  muzzle:
    needs: setup-muzzle-matrix
    runs-on: ubuntu-24.04
    strategy:
      matrix: ${{fromJson(needs.setup-muzzle-matrix.outputs.matrix)}}
      fail-fast: false
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up JDK 17 for running Gradle
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0

      - name: Run muzzle
        # using retry because of sporadic gradle download failures
        uses: nick-invision/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4.0.0
        with:
          # timing out has not been a problem, these jobs typically finish in 2-3 minutes
          timeout_minutes: 15
          max_attempts: 3
          command: ./gradlew ${{ matrix.module }}:muzzle --stacktrace

  smoke-test:
    runs-on: ${{ matrix.os }}
    permissions:
      packages: read
    strategy:
      matrix:
        os: [ windows-2025, ubuntu-24.04 ]
        suite: [ "glassfish", "jboss", "jetty", "liberty", "profiler", "tomcat", "tomee", "weblogic", "websphere", "wildfly", "other" ]
        exclude:
          - os: windows-2025
            suite: websphere
          - os: windows-2025
            suite: profiler
      fail-fast: false
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Free disk space
        run: .github/scripts/gha-free-disk-space.sh

      - name: Docker issue workaround
        if: startsWith(matrix.os, 'windows')
        run: |
          $dockerState = Get-Service -Name "docker"
          if ($dockerState.Status -ne "Running") {
            Start-Service -Name "docker"
          }

      - name: Set up JDK 17 for running Gradle
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@abd2ef45e78c5afb21d64d4ca52ee8550d9572c7 # v4.5.1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: startsWith(matrix.os, 'ubuntu')

      - name: Pull proprietary images
        run: ./gradlew pullProprietaryTestImages
        if: startsWith(matrix.os, 'ubuntu')

      - name: Test
        run: ./gradlew :smoke-tests:test -PsmokeTestSuite=${{ matrix.suite }}

      - name: Build scan
        if: ${{ !cancelled() && hashFiles('build-scan.txt') != '' }}
        run: cat build-scan.txt

  shellcheck:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install shell check
        run: wget -qO- "https://github.com/koalaman/shellcheck/releases/download/v0.8.0/shellcheck-v0.8.0.linux.x86_64.tar.xz" | tar -xJv

      - name: Run shellcheck
        run: shellcheck-v0.8.0/shellcheck --format=gcc $(find scripts -name '*.sh')
