name: Build splunk-otel-collector Windows docker image

on:
  push:
    paths:
      - 'smoke-tests/otel-collector-contrib-windows/**'
      - '.github/workflows/publish-otel-collector-contrib-windows.yaml'
    branches: [ 'main' ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    permissions:
      packages: write
      contents: read
    steps:
      - name: Support longpaths
        run: git config --system core.longpaths true

      - uses: actions/checkout@v3

      - name: Login to GitHub Package Registry
        uses: azure/docker-login@v1
        with:
          login-server: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push docker image
        run: ./build.sh "$GITHUB_RUN_ID"
        working-directory: smoke-tests/otel-collector-contrib-windows
