name: Request PR review from signalfx/gdi-java-approvers

on:
  pull_request:
    types: [ opened ]

jobs:
  request:
    name: Request PR review from signalfx/gdi-java-approvers
    runs-on: ubuntu-20.04
    permissions:
      issues: write
    steps:
      - name: Add signalfx/gdi-java-approvers as reviewers
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr edit ${{ github.event.pull_request.html_url }} \
              --add-reviewer signalfx/gdi-java-approvers
